### PR TITLE
Update no-undef.js

### PR DESCRIPTION
**Pull request by ronapelbaum**
# propose to fix issue #4

### CODE REVIEW

**Comment by jschaf** [comment]
Thank you for the commit.

**Comment by jschaf** [comment]
Ah yes, thanks for the reminder.  Just published it as v0.1.0.

**Comment by ronapelbaum** [comment]
I still don't see it in `npmjs`...
https://www.npmjs.com/package/eslint-plugin-closure

**Comment by jschaf** [comment]
Ah, I see. This package is published as
https://www.npmjs.com/package/eslint-closure (no -plugin)

**Comment by jschaf** [comment]
I think I just need to publish the subpackages.  Gimme one sec.

**Comment by jschaf** [comment]
Ok, everything is updated to v0.1.1

**Comment by ronapelbaum** [comment]
Hi @jschaf 
it appears that although you've re-published the package, the `dist/closure-eslint-plugin.js` still doesn't contain my changes..

**Pull request merged**
